#! /bin/sh

# Launch compton
compton -b

# Launch mpd
mpd &

#
# Per-machine Configuration
# (Do this first to avoid the ugly grey screen)
#

case $(hostname) in

    howlback)
        # Launch gebaar
        sh /home/will/.config/gebaar/launch.sh

        # Launch batt
        batt &

        # Launch polybar
        sh .config/polybar/launch.sh goldenarches

        # Set wallpaper
        feh --no-fehbg --bg-center ~/.wallpapers/doom_mild.png

        # Configure desktops
        bspc monitor -d I II III IV V VI VII VIII IX X

        ;;


    shadowboxpc)
        # Launch polybar
        sh .config/polybar/launch.sh shadowboxpc-main shadowboxpc-side 

        # Set wallpaper
        feh --no-fehbg --bg-center ~/.wallpapers/doom.2560x1080.jpg

        # Configure desktops
        bspc monitor -d I II III IV V VI VII VIII IX X

        ;;
esac

#
# Launch programs
#

# Launch SXHKD
sxhkd &

# Launch dunst
dunst &

# Launch syncthing
syncthing -no-browser &

# Mute sound on boot
ponymix mute

# Disable screen saver blanking
xset s off -dpms

#
# BSPWM initialization
#

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config initial_polarity second_child

bspc rule -a '*:libreofficedev' state=tiled
bspc rule -a '*:soffice' state=tiled
bspc rule -a '*:zathura' state=tiled
bspc rule -a '*:emacs' state=tiled
