#! /bin/sh

# Launch SXHKD
sxhkd &

# Launch mpd
mpd &

# Launch compton
compton -b

# Launch dunst
dunst &

# Launch gebaar
sh /home/will/.config/gebaar/launch.sh

# Launch nitrogen with the last selected wallpaper
nitrogen --restore &

# Launch polybar with the correct configuration
sh /home/will/.config/polybar/launch.sh

# Launch dropbox
/usr/bin/dropbox &

# Mute sound on boot
amixer sset Master mute

# Disable screen saver blanking
xset s off -dpms

#
# BSPWM initialization
#
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config initial_polarity second_child

bspc rule -a '*:libreofficedev' state=tiled
bspc rule -a '*:soffice' state=tiled
bspc rule -a '*:zathura' state=tiled
