#! /bin/sh

# Launch SXHKD
sxhkd &

# Launch compton
compton -b

# Launch dunst
dunst &

# Launch polybar with the correct configuration
sh /home/will/.config/polybar/launch.sh

# Launch syncthing
syncthing -no-browser &

# Mute sound on boot
ponymix mute

# Disable screen saver blanking
xset s off -dpms

# Launch emacs in daemon mode
emacs --daemon &

#
# Per-machine Configuration
#

case $(hostname) in
    goldenarches)
        # Launch gebaar
        sh /home/will/.config/gebaar/launch.sh

        # Launch mpd
        mpd &

        # Launch batt
        batt &

        # Launch polybar
        sh .config/polybar/launch.sh goldenarches

        # Set wallpaper
        feh --no-fehbg --bg-center ~/.wallpapers/l_garage01_big.jpg

        # Configure desktops
        bspc monitor -d I II III IV V VI VII VIII IX X

        ;;


    shadowboxpc)
        # Launch polybar
        sh .config/polybar/launch.sh shadowboxpc-main shadowboxpc-side 

        # Set wallpaper
        feh --no-fehbg --bg-center ~/.wallpapers/l_ash03_big.1920x1080.jpg ~/.wallpapers/l_ash06_big.1920x1080.jpg

        # Configure desktops
        bspc monitor DVI-D-0 -d I II III IV V VI VII
        bspc monitor HDMI-0 -d VIII IX X
        ;;
esac


#
# BSPWM initialization
#

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config initial_polarity second_child

bspc rule -a '*:libreofficedev' state=tiled
bspc rule -a '*:soffice' state=tiled
bspc rule -a '*:zathura' state=tiled
bspc rule -a '*:emacs' state=tiled
