#!/bin/sh
setxkbmap -option caps:escape -option compose:ralt

userresources="$XDG_CONFIG_HOME/X11/xresources"
usermodmap="$XDG_CONFIG_HOME/X11/xmodmap"
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# Fix java windows
export AWT_TOOLKIT=MToolkit
export _JAVA_AWT_WM_NONREPARENTING=1

# Fix font scaling on alacritty
if [ "$(hostname)" = howlback ]; then
    export WINIT_X11_SCALE_FACTOR=1
fi

# Fix QT scaling issues; their DPI measurements do not work
export QT_AUTO_SCREEN_SCALE_FACTOR=0

source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

# Launch the window manager
exec bspwm 2>&1
