#! /bin/sh

#
# Per-machine Configuration
# (Do this first to avoid the ugly grey screen)
#

case $(hostname) in

    howlback)
        # Set wallpaper
        feh -Z --scale-down --no-fehbg --bg-fill ~/documents/wallpapers/mandalorian.jpg &

        # Launch polybar
        sh .config/polybar/launch.sh goldenarches &

        # Launch batt
        batt &

        # Configure desktops
        bspc monitor -d I II III IV V VI VII VIII IX X

        # Launch picom
        picom -b --backend glx

        ;;


    novastorm)
        # Set wallpaper
        feh -Z --scale-down --no-fehbg --bg-center ~/documents/wallpapers/stormtroopers.2560x1080.jpg &

        # Launch polybar
        sh .config/polybar/launch.sh novastorm &

        # Configure desktops
        bspc monitor -d I II III IV V VI VII VIII IX X

        # Launch picom
        picom -b --backend xrender

        ;;
esac

#
# Launch programs
#

# Launch SXHKD
sxhkd &

# Launch dunst
dunst &

# Launch nextcloud
nextcloud &

# Mute sound on boot
ponymix mute

# Disable screen saver blanking
xset s off -dpms

#
# BSPWM initialization
#

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config initial_polarity second_child

bspc rule -a '*:libreofficedev' state=tiled
bspc rule -a '*:soffice' state=tiled
bspc rule -a Zathura state=tiled
